version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./migration/create-table-macapa.sql:/docker-entrypoint-initdb.d/create-table-macapa.sql

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "admin"
    volumes: 
      - ./migration/create-table-varejao.sql:/docker-entrypoint-initdb.d/create-table-varejao.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgresql
